export const SUPPLIER_LANGUAGES = ['en', 'nl', 'fr', 'es', 'pt'] as const;

export type SupplierLanguage = (typeof SUPPLIER_LANGUAGES)[number];

export const SUPPLIER_LANGUAGE_LABELS: Record<SupplierLanguage, string> = {
  en: 'English',
  nl: 'Nederlands',
  fr: 'Français',
  es: 'Español',
  pt: 'Português',
};

export const SUPPLIER_LANGUAGE_LOCALES: Record<SupplierLanguage, string> = {
  en: 'en-GB',
  nl: 'nl-BE',
  fr: 'fr-FR',
  es: 'es-ES',
  pt: 'pt-PT',
};

export function normalizeSupplierLanguage(value: unknown): SupplierLanguage {
  return SUPPLIER_LANGUAGES.includes(value as SupplierLanguage) ? (value as SupplierLanguage) : 'en';
}

export function translateUsageEnvironment(value: 'Indoor' | 'Outdoor' | null | undefined, language: SupplierLanguage) {
  if (!value) {
    return null;
  }

  const labels: Record<SupplierLanguage, Record<'Indoor' | 'Outdoor', string>> = {
    en: { Indoor: 'Indoor', Outdoor: 'Outdoor' },
    nl: { Indoor: 'Binnen', Outdoor: 'Buiten' },
    fr: { Indoor: 'Intérieur', Outdoor: 'Extérieur' },
    es: { Indoor: 'Interior', Outdoor: 'Exterior' },
    pt: { Indoor: 'Interior', Outdoor: 'Exterior' },
  };

  return labels[language][value];
}

export const supplierTranslations = {
  en: {
    requestForQuotation: 'Request for quotation',
    newRequestForQuotation: 'New request for quotation',
    dear: 'Dear',
    emailIntroDefault: (material: string, shape: string) =>
      `There is a new request for quotation for <strong>${material}</strong> (${shape}).`,
    emailIntroTableTop: 'There is a new request for quotation for a <strong>table top</strong>.',
    emailIntroTableFoot: 'There is a new request for quotation for a <strong>table foot</strong>.',
    emailIntroTableBoth: 'There is a new combined request for quotation for a <strong>table top and table foot</strong>.',
    clickToView: 'Click the link below to view the request and submit a quote:',
    submitQuote: 'Submit quote',
    updateQuote: 'Update quote',
    linkValid: 'This link is valid for 30 days.',
    invalidLinkTitle: 'Invalid link',
    invalidLinkMessage: 'This link does not include an access token. Open the latest email invite and try again.',
    accessDenied: 'Access denied',
    material: 'Material',
    finish: 'Finish',
    topFinish: 'Top finish',
    edgeFinish: 'Edge finish',
    colorFinish: 'Color finish',
    tableTop: 'Table top',
    tableFoot: 'Table foot',
    tableTopAndFoot: 'Table top + table foot',
    part: 'Part',
    productType: 'Product type',
    shape: 'Shape',
    use: 'Use',
    model: 'Model',
    dimensions: 'Dimensions',
    dimensionsRound: 'Dimensions (Ø x H)',
    dimensionsDefault: 'Dimensions (LxWxH)',
    quantity: 'Quantity',
    thicknessTop: 'Thickness top',
    notes: 'Notes',
    attachments: 'Attachments',
    open: 'Open',
    opening: 'Opening...',
    couldNotOpenAttachment: 'Could not open attachment.',
    basePrice: 'Base price',
    basePriceEur: 'Base price (EUR) *',
    volumeM3: 'Volume (m³)',
    volumeM3Required: 'Volume (m³) *',
    leadTime: 'Lead time',
    leadTimeOptional: 'Lead time (days, optional)',
    days: 'days',
    comment: 'Comment',
    commentOptional: 'Comment (optional)',
    submitting: 'Submitting...',
    quoteSubmitted: 'Quote submitted',
    quoteUpdated: 'Quote updated',
    quoteSubmittedThanks: 'Thank you for your quote. You can close this page.',
    quoteUpdatedThanks: 'Your latest quote has been saved. You can close this page.',
    yourSubmittedQuote: 'Your submitted quote',
    submittedOn: 'Submitted on',
    conversation: 'Conversation',
    noMessagesYet: 'No messages yet.',
    sempreTeam: 'Sempre team',
    you: 'You',
    messageRequired: 'Message is required',
    couldNotSendMessage: 'Could not send message',
    messagePlaceholder: 'Ask a question or share an update...',
    sending: 'Sending...',
    sendMessage: 'Send message',
    na: 'N/A',
  },
  nl: {
    requestForQuotation: 'Prijsaanvraag',
    newRequestForQuotation: 'Nieuwe prijsaanvraag',
    dear: 'Beste',
    emailIntroDefault: (material: string, shape: string) =>
      `Er is een nieuwe prijsaanvraag voor <strong>${material}</strong> (${shape}).`,
    emailIntroTableTop: 'Er is een nieuwe prijsaanvraag voor een <strong>tafelblad</strong>.',
    emailIntroTableFoot: 'Er is een nieuwe prijsaanvraag voor een <strong>tafelvoet</strong>.',
    emailIntroTableBoth: 'Er is een nieuwe gecombineerde prijsaanvraag voor een <strong>tafelblad en tafelvoet</strong>.',
    clickToView: 'Klik op de link hieronder om de aanvraag te bekijken en een offerte in te dienen:',
    submitQuote: 'Offerte indienen',
    updateQuote: 'Offerte bijwerken',
    linkValid: 'Deze link is 30 dagen geldig.',
    invalidLinkTitle: 'Ongeldige link',
    invalidLinkMessage: 'Deze link bevat geen toegangstoken. Open de laatste e-mailuitnodiging en probeer opnieuw.',
    accessDenied: 'Toegang geweigerd',
    material: 'Materiaal',
    finish: 'Afwerking',
    topFinish: 'Bovenafwerking',
    edgeFinish: 'Randafwerking',
    colorFinish: 'Kleurafwerking',
    tableTop: 'Tafelblad',
    tableFoot: 'Tafelvoet',
    tableTopAndFoot: 'Tafelblad + tafelvoet',
    part: 'Onderdeel',
    productType: 'Producttype',
    shape: 'Vorm',
    use: 'Gebruik',
    model: 'Model',
    dimensions: 'Afmetingen',
    dimensionsRound: 'Afmetingen (Ø x H)',
    dimensionsDefault: 'Afmetingen (LxBxH)',
    quantity: 'Aantal',
    thicknessTop: 'Dikte blad',
    notes: 'Opmerkingen',
    attachments: 'Bijlagen',
    open: 'Openen',
    opening: 'Openen...',
    couldNotOpenAttachment: 'Bijlage kon niet geopend worden.',
    basePrice: 'Basisprijs',
    basePriceEur: 'Basisprijs (EUR) *',
    volumeM3: 'Volume (m³)',
    volumeM3Required: 'Volume (m³) *',
    leadTime: 'Levertijd',
    leadTimeOptional: 'Levertijd (dagen, optioneel)',
    days: 'dagen',
    comment: 'Opmerking',
    commentOptional: 'Opmerking (optioneel)',
    submitting: 'Indienen...',
    quoteSubmitted: 'Offerte ingediend',
    quoteUpdated: 'Offerte bijgewerkt',
    quoteSubmittedThanks: 'Bedankt voor uw offerte. U mag deze pagina sluiten.',
    quoteUpdatedThanks: 'Uw laatste offerte werd opgeslagen. U mag deze pagina sluiten.',
    yourSubmittedQuote: 'Uw ingediende offerte',
    submittedOn: 'Ingediend op',
    conversation: 'Conversatie',
    noMessagesYet: 'Nog geen berichten.',
    sempreTeam: 'Sempre team',
    you: 'U',
    messageRequired: 'Bericht is verplicht',
    couldNotSendMessage: 'Bericht kon niet verzonden worden',
    messagePlaceholder: 'Stel een vraag of deel een update...',
    sending: 'Verzenden...',
    sendMessage: 'Bericht verzenden',
    na: 'N.v.t.',
  },
  fr: {
    requestForQuotation: 'Demande de prix',
    newRequestForQuotation: 'Nouvelle demande de prix',
    dear: 'Bonjour',
    emailIntroDefault: (material: string, shape: string) =>
      `Nous avons une nouvelle demande de prix pour <strong>${material}</strong> (${shape}).`,
    emailIntroTableTop: 'Nous avons une nouvelle demande de prix pour un <strong>plateau de table</strong>.',
    emailIntroTableFoot: 'Nous avons une nouvelle demande de prix pour un <strong>pied de table</strong>.',
    emailIntroTableBoth: 'Nous avons une nouvelle demande de prix combinée pour un <strong>plateau et un pied de table</strong>.',
    clickToView: 'Cliquez sur le lien ci-dessous pour consulter la demande et soumettre votre offre :',
    submitQuote: 'Soumettre une offre',
    updateQuote: 'Mettre à jour l’offre',
    linkValid: 'Ce lien est valable pendant 30 jours.',
    invalidLinkTitle: 'Lien invalide',
    invalidLinkMessage: 'Ce lien ne contient pas de jeton d’accès. Ouvrez la dernière invitation par e-mail et réessayez.',
    accessDenied: 'Accès refusé',
    material: 'Matériau',
    finish: 'Finition',
    topFinish: 'Finition supérieure',
    edgeFinish: 'Finition du chant',
    colorFinish: 'Finition couleur',
    tableTop: 'Plateau de table',
    tableFoot: 'Pied de table',
    tableTopAndFoot: 'Plateau + pied de table',
    part: 'Partie',
    productType: 'Type de produit',
    shape: 'Forme',
    use: 'Usage',
    model: 'Modèle',
    dimensions: 'Dimensions',
    dimensionsRound: 'Dimensions (Ø x H)',
    dimensionsDefault: 'Dimensions (LxlxH)',
    quantity: 'Quantité',
    thicknessTop: 'Épaisseur du plateau',
    notes: 'Remarques',
    attachments: 'Pièces jointes',
    open: 'Ouvrir',
    opening: 'Ouverture...',
    couldNotOpenAttachment: 'Impossible d’ouvrir la pièce jointe.',
    basePrice: 'Prix de base',
    basePriceEur: 'Prix de base (EUR) *',
    volumeM3: 'Volume (m³)',
    volumeM3Required: 'Volume (m³) *',
    leadTime: 'Délai',
    leadTimeOptional: 'Délai (jours, optionnel)',
    days: 'jours',
    comment: 'Commentaire',
    commentOptional: 'Commentaire (optionnel)',
    submitting: 'Envoi...',
    quoteSubmitted: 'Offre soumise',
    quoteUpdated: 'Offre mise à jour',
    quoteSubmittedThanks: 'Merci pour votre offre. Vous pouvez fermer cette page.',
    quoteUpdatedThanks: 'Votre dernière offre a été enregistrée. Vous pouvez fermer cette page.',
    yourSubmittedQuote: 'Votre offre soumise',
    submittedOn: 'Soumise le',
    conversation: 'Conversation',
    noMessagesYet: 'Aucun message pour le moment.',
    sempreTeam: 'Équipe Sempre',
    you: 'Vous',
    messageRequired: 'Le message est obligatoire',
    couldNotSendMessage: 'Impossible d’envoyer le message',
    messagePlaceholder: 'Posez une question ou partagez une mise à jour...',
    sending: 'Envoi...',
    sendMessage: 'Envoyer le message',
    na: 'N/A',
  },
  es: {
    requestForQuotation: 'Solicitud de cotización',
    newRequestForQuotation: 'Nueva solicitud de cotización',
    dear: 'Hola',
    emailIntroDefault: (material: string, shape: string) =>
      `Hay una nueva solicitud de cotización para <strong>${material}</strong> (${shape}).`,
    emailIntroTableTop: 'Hay una nueva solicitud de cotización para un <strong>tablero de mesa</strong>.',
    emailIntroTableFoot: 'Hay una nueva solicitud de cotización para una <strong>base de mesa</strong>.',
    emailIntroTableBoth: 'Hay una nueva solicitud de cotización combinada para un <strong>tablero y una base de mesa</strong>.',
    clickToView: 'Haga clic en el enlace siguiente para ver la solicitud y enviar una cotización:',
    submitQuote: 'Enviar cotización',
    updateQuote: 'Actualizar cotización',
    linkValid: 'Este enlace es válido durante 30 días.',
    invalidLinkTitle: 'Enlace no válido',
    invalidLinkMessage: 'Este enlace no incluye un token de acceso. Abra la última invitación por correo e inténtelo de nuevo.',
    accessDenied: 'Acceso denegado',
    material: 'Material',
    finish: 'Acabado',
    topFinish: 'Acabado superior',
    edgeFinish: 'Acabado del canto',
    colorFinish: 'Acabado de color',
    tableTop: 'Tablero de mesa',
    tableFoot: 'Base de mesa',
    tableTopAndFoot: 'Tablero + base de mesa',
    part: 'Parte',
    productType: 'Tipo de producto',
    shape: 'Forma',
    use: 'Uso',
    model: 'Modelo',
    dimensions: 'Dimensiones',
    dimensionsRound: 'Dimensiones (Ø x H)',
    dimensionsDefault: 'Dimensiones (LxAnxAl)',
    quantity: 'Cantidad',
    thicknessTop: 'Grosor del tablero',
    notes: 'Notas',
    attachments: 'Adjuntos',
    open: 'Abrir',
    opening: 'Abriendo...',
    couldNotOpenAttachment: 'No se pudo abrir el adjunto.',
    basePrice: 'Precio base',
    basePriceEur: 'Precio base (EUR) *',
    volumeM3: 'Volumen (m³)',
    volumeM3Required: 'Volumen (m³) *',
    leadTime: 'Plazo de entrega',
    leadTimeOptional: 'Plazo de entrega (días, opcional)',
    days: 'días',
    comment: 'Comentario',
    commentOptional: 'Comentario (opcional)',
    submitting: 'Enviando...',
    quoteSubmitted: 'Cotización enviada',
    quoteUpdated: 'Cotización actualizada',
    quoteSubmittedThanks: 'Gracias por su cotización. Puede cerrar esta página.',
    quoteUpdatedThanks: 'Su última cotización se ha guardado. Puede cerrar esta página.',
    yourSubmittedQuote: 'Su cotización enviada',
    submittedOn: 'Enviada el',
    conversation: 'Conversación',
    noMessagesYet: 'Aún no hay mensajes.',
    sempreTeam: 'Equipo Sempre',
    you: 'Usted',
    messageRequired: 'El mensaje es obligatorio',
    couldNotSendMessage: 'No se pudo enviar el mensaje',
    messagePlaceholder: 'Haga una pregunta o comparta una actualización...',
    sending: 'Enviando...',
    sendMessage: 'Enviar mensaje',
    na: 'N/D',
  },
  pt: {
    requestForQuotation: 'Pedido de cotação',
    newRequestForQuotation: 'Novo pedido de cotação',
    dear: 'Olá',
    emailIntroDefault: (material: string, shape: string) =>
      `Existe um novo pedido de cotação para <strong>${material}</strong> (${shape}).`,
    emailIntroTableTop: 'Existe um novo pedido de cotação para um <strong>tampo de mesa</strong>.',
    emailIntroTableFoot: 'Existe um novo pedido de cotação para uma <strong>base de mesa</strong>.',
    emailIntroTableBoth: 'Existe um novo pedido de cotação combinado para um <strong>tampo e uma base de mesa</strong>.',
    clickToView: 'Clique no link abaixo para ver o pedido e submeter uma cotação:',
    submitQuote: 'Submeter cotação',
    updateQuote: 'Atualizar cotação',
    linkValid: 'Este link é válido durante 30 dias.',
    invalidLinkTitle: 'Link inválido',
    invalidLinkMessage: 'Este link não inclui um token de acesso. Abra o convite de e-mail mais recente e tente novamente.',
    accessDenied: 'Acesso negado',
    material: 'Material',
    finish: 'Acabamento',
    topFinish: 'Acabamento superior',
    edgeFinish: 'Acabamento da borda',
    colorFinish: 'Acabamento de cor',
    tableTop: 'Tampo de mesa',
    tableFoot: 'Base de mesa',
    tableTopAndFoot: 'Tampo + base de mesa',
    part: 'Parte',
    productType: 'Tipo de produto',
    shape: 'Forma',
    use: 'Uso',
    model: 'Modelo',
    dimensions: 'Dimensões',
    dimensionsRound: 'Dimensões (Ø x A)',
    dimensionsDefault: 'Dimensões (CxLxA)',
    quantity: 'Quantidade',
    thicknessTop: 'Espessura do tampo',
    notes: 'Notas',
    attachments: 'Anexos',
    open: 'Abrir',
    opening: 'A abrir...',
    couldNotOpenAttachment: 'Não foi possível abrir o anexo.',
    basePrice: 'Preço base',
    basePriceEur: 'Preço base (EUR) *',
    volumeM3: 'Volume (m³)',
    volumeM3Required: 'Volume (m³) *',
    leadTime: 'Prazo de entrega',
    leadTimeOptional: 'Prazo de entrega (dias, opcional)',
    days: 'dias',
    comment: 'Comentário',
    commentOptional: 'Comentário (opcional)',
    submitting: 'A submeter...',
    quoteSubmitted: 'Cotação submetida',
    quoteUpdated: 'Cotação atualizada',
    quoteSubmittedThanks: 'Obrigado pela sua cotação. Pode fechar esta página.',
    quoteUpdatedThanks: 'A sua cotação mais recente foi guardada. Pode fechar esta página.',
    yourSubmittedQuote: 'A sua cotação submetida',
    submittedOn: 'Submetida em',
    conversation: 'Conversa',
    noMessagesYet: 'Ainda não há mensagens.',
    sempreTeam: 'Equipa Sempre',
    you: 'Você',
    messageRequired: 'A mensagem é obrigatória',
    couldNotSendMessage: 'Não foi possível enviar a mensagem',
    messagePlaceholder: 'Faça uma pergunta ou partilhe uma atualização...',
    sending: 'A enviar...',
    sendMessage: 'Enviar mensagem',
    na: 'N/A',
  },
} as const;

export type SupplierTranslation = (typeof supplierTranslations)[SupplierLanguage];

export function getSupplierTranslations(language: SupplierLanguage) {
  return supplierTranslations[language];
}
